export const ADD_PRODUCT="ADD_PRODUCT";
export const ADD_PRODUCT_ERROR="ADD_PRODUCT_ERROR";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const EDIT_PRODUCT="EDIT_PRODUCT";
export const FETCH_PRODUCTS_LODING="FETCH_PRODUCTS_LODING";
export const FETCH_PRODUCTS_SUCCSES="FETCH_PRODUCTS_SUCCSES";
export const FETCH_PRODUCTS_FAILER="FETCH_PRODUCTS_FAILER";